[pytest]
asyncio_mode = auto
addopts =
    --alluredir=allure-results
    --clean-alluredir
    -v
    --base-url=https://www.demoblaze.com
testpaths = tests



[playwright]
browser = chromium
base_url = https://www.demoblaze.com
